# E1 213 Pattern Recognition and Neural Network - Assignment 1
***
*Submitted by: Dwaipayan Haldar*<br>
*S.R. No. : 27128*

In [3]:
import numpy as np
import os
import matplotlib.pyplot as plt

from src import *

### Phase 1: Bio-Optic Sensor Calibration

In [2]:
data = load_data('dataset_1.csv')

#### Problem 1.1

In [3]:
model = ordinary_least_squares()
W_1 = model.gradient_descent_fit(data[:,0],data[:,1])
W_2 = model.normal_equation_fit(data[:,0],data[:,1])

print(f"L2 norm of the difference of the final weight vectors is {np.linalg.norm(W_1-W_2)}")

L2 norm of the difference of the final weight vectors is 1.6207735234714224e-14


#### Problem 1.2

In [10]:
X = data[:,0]
y = data[:,1]
y_binary = np.where(y>=np.median(y),1,-1)

model = hard_margin_svm(X, y_binary)

mu = model.optimal_mu()

index = np.where(mu>0,1,0)
print(np.unique(index, return_counts=True))

     pcost       dcost       gap    pres   dres
 0: -1.2401e+03 -2.6033e+03  2e+04  1e+02  2e+00
 1: -2.7096e+03 -3.3614e+03  1e+04  6e+01  1e+00
 2: -3.5991e+03 -4.4456e+03  1e+04  6e+01  1e+00
 3: -4.3407e+03 -5.3609e+03  1e+04  6e+01  1e+00
 4: -4.6635e+04 -5.6129e+04  1e+04  6e+01  1e+00
 5: -3.0298e+05 -3.0963e+05  7e+03  5e+01  1e+00
 6: -1.3871e+06 -1.4153e+06  3e+04  5e+01  1e+00
 7: -2.8324e+06 -2.8887e+06  6e+04  5e+01  1e+00
 8: -2.9091e+06 -2.9669e+06  6e+04  5e+01  1e+00
 9: -1.4993e+08 -1.4998e+08  5e+04  5e+01  1e+00
10: -1.6865e+11 -1.6869e+11  4e+07  5e+01  1e+00
11: -2.8348e+11 -2.8354e+11  6e+07  5e+01  1e+00
12: -3.9382e+11 -3.9390e+11  8e+07  5e+01  1e+00
13: -4.0845e+11 -4.0853e+11  8e+07  5e+01  1e+00
14: -6.0153e+11 -6.0164e+11  1e+08  5e+01  1e+00
15: -8.8230e+11 -8.8244e+11  1e+08  5e+01  1e+00
16: -1.9809e+12 -1.9810e+12  1e+08  5e+01  1e+00
Terminated (singular KKT matrix).
(array([1]), array([5000]))


### Phase 2: Oncology Array

#### Problem 2.3

In [11]:
data_2 = load_data('dataset_2.csv')

In [33]:
data_3 = load_data('dataset_3.csv')

X = data_3[:,:-1]

X[0,:].shape

(50,)

In [19]:
y[y ==1] = 0
y[y == 2] = 1

np.unique(y, return_counts= True)

(array([0., 1.]), array([5000, 5000]))

array([1., 2., 2., ..., 0., 0., 0.])

In [42]:
N = X.shape[0]
K = 5
idx = np.random.randint(0,N, size=(K))
mu = X[idx]
mu[0].shape

(50,)

In [48]:
f = np.random.rand(K,)
sigma = [s*np.eye(X.shape[1]) for s in f]

In [49]:
sigma

[array([[0.19365728, 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.19365728, 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.19365728, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.19365728, 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.19365728,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.19365728]]),
 array([[0.448742, 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
        [0.      , 0.448742, 0.      , ..., 0.      , 0.      , 0.      ],
        [0.      , 0.      , 0.448742, ..., 0.      , 0.      , 0.      ],
        ...,
        [0.      , 0.      , 0.      , ..., 0.448742, 0.      , 0.      ],
        [0.      , 0.      , 0.      , ..., 0.      , 0.448742, 0.      ],
        [0.      , 0.